export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_ACCESS_DENIED = 'PROJECT_ACCESS_DENIED',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  CHECKLIST_ITEM_NOT_FOUND = 'CHECKLIST_ITEM_NOT_FOUND',
  FLOOR_PLAN_NOT_FOUND = 'FLOOR_PLAN_NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  INVALID_INPUT = 'INVALID_INPUT',
  DATABASE_ERROR = 'DATABASE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  VALIDATION_ERROR = 'VALIDATION_ERROR'
}

export enum HttpStatus {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500
}

export const ERROR_HTTP_STATUS_MAP: Record<ErrorCode, HttpStatus> = {
  [ErrorCode.USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.USER_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [ErrorCode.PROJECT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.PROJECT_ACCESS_DENIED]: HttpStatus.FORBIDDEN,
  [ErrorCode.TASK_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.CHECKLIST_ITEM_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.FLOOR_PLAN_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.ROOM_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.INVALID_INPUT]: HttpStatus.BAD_REQUEST,
  [ErrorCode.DATABASE_ERROR]: HttpStatus.INTERNAL_SERVER_ERROR,
  [ErrorCode.NETWORK_ERROR]: HttpStatus.INTERNAL_SERVER_ERROR,
  [ErrorCode.PERMISSION_DENIED]: HttpStatus.FORBIDDEN,
  [ErrorCode.VALIDATION_ERROR]: HttpStatus.BAD_REQUEST
};